/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-pagerduty-api/apis/response/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePlays implements PlayInterface
type FakePlays struct {
	Fake *FakeResponseV1alpha1
	ns   string
}

var playsResource = schema.GroupVersionResource{Group: "response.pagerduty.kubeform.com", Version: "v1alpha1", Resource: "plays"}

var playsKind = schema.GroupVersionKind{Group: "response.pagerduty.kubeform.com", Version: "v1alpha1", Kind: "Play"}

// Get takes name of the play, and returns the corresponding play object, and an error if there is any.
func (c *FakePlays) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Play, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(playsResource, c.ns, name), &v1alpha1.Play{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Play), err
}

// List takes label and field selectors, and returns the list of Plays that match those selectors.
func (c *FakePlays) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PlayList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(playsResource, playsKind, c.ns, opts), &v1alpha1.PlayList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PlayList{ListMeta: obj.(*v1alpha1.PlayList).ListMeta}
	for _, item := range obj.(*v1alpha1.PlayList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested plays.
func (c *FakePlays) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(playsResource, c.ns, opts))

}

// Create takes the representation of a play and creates it.  Returns the server's representation of the play, and an error, if there is any.
func (c *FakePlays) Create(ctx context.Context, play *v1alpha1.Play, opts v1.CreateOptions) (result *v1alpha1.Play, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(playsResource, c.ns, play), &v1alpha1.Play{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Play), err
}

// Update takes the representation of a play and updates it. Returns the server's representation of the play, and an error, if there is any.
func (c *FakePlays) Update(ctx context.Context, play *v1alpha1.Play, opts v1.UpdateOptions) (result *v1alpha1.Play, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(playsResource, c.ns, play), &v1alpha1.Play{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Play), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePlays) UpdateStatus(ctx context.Context, play *v1alpha1.Play, opts v1.UpdateOptions) (*v1alpha1.Play, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(playsResource, "status", c.ns, play), &v1alpha1.Play{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Play), err
}

// Delete takes name of the play and deletes it. Returns an error if one occurs.
func (c *FakePlays) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(playsResource, c.ns, name), &v1alpha1.Play{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePlays) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(playsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PlayList{})
	return err
}

// Patch applies the patch and returns the patched play.
func (c *FakePlays) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Play, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(playsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Play{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Play), err
}
