/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-pagerduty-api/apis/extension/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServicenows implements ServicenowInterface
type FakeServicenows struct {
	Fake *FakeExtensionV1alpha1
	ns   string
}

var servicenowsResource = schema.GroupVersionResource{Group: "extension.pagerduty.kubeform.com", Version: "v1alpha1", Resource: "servicenows"}

var servicenowsKind = schema.GroupVersionKind{Group: "extension.pagerduty.kubeform.com", Version: "v1alpha1", Kind: "Servicenow"}

// Get takes name of the servicenow, and returns the corresponding servicenow object, and an error if there is any.
func (c *FakeServicenows) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Servicenow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicenowsResource, c.ns, name), &v1alpha1.Servicenow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Servicenow), err
}

// List takes label and field selectors, and returns the list of Servicenows that match those selectors.
func (c *FakeServicenows) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServicenowList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicenowsResource, servicenowsKind, c.ns, opts), &v1alpha1.ServicenowList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServicenowList{ListMeta: obj.(*v1alpha1.ServicenowList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServicenowList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested servicenows.
func (c *FakeServicenows) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicenowsResource, c.ns, opts))

}

// Create takes the representation of a servicenow and creates it.  Returns the server's representation of the servicenow, and an error, if there is any.
func (c *FakeServicenows) Create(ctx context.Context, servicenow *v1alpha1.Servicenow, opts v1.CreateOptions) (result *v1alpha1.Servicenow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicenowsResource, c.ns, servicenow), &v1alpha1.Servicenow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Servicenow), err
}

// Update takes the representation of a servicenow and updates it. Returns the server's representation of the servicenow, and an error, if there is any.
func (c *FakeServicenows) Update(ctx context.Context, servicenow *v1alpha1.Servicenow, opts v1.UpdateOptions) (result *v1alpha1.Servicenow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicenowsResource, c.ns, servicenow), &v1alpha1.Servicenow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Servicenow), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServicenows) UpdateStatus(ctx context.Context, servicenow *v1alpha1.Servicenow, opts v1.UpdateOptions) (*v1alpha1.Servicenow, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(servicenowsResource, "status", c.ns, servicenow), &v1alpha1.Servicenow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Servicenow), err
}

// Delete takes name of the servicenow and deletes it. Returns an error if one occurs.
func (c *FakeServicenows) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(servicenowsResource, c.ns, name), &v1alpha1.Servicenow{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServicenows) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicenowsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServicenowList{})
	return err
}

// Patch applies the patch and returns the patched servicenow.
func (c *FakeServicenows) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Servicenow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicenowsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Servicenow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Servicenow), err
}
