/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1alpha1 "kubeform.dev/provider-pagerduty-api/apis/addon/v1alpha1"
	businessv1alpha1 "kubeform.dev/provider-pagerduty-api/apis/business/v1alpha1"
	escalationv1alpha1 "kubeform.dev/provider-pagerduty-api/apis/escalation/v1alpha1"
	eventv1alpha1 "kubeform.dev/provider-pagerduty-api/apis/event/v1alpha1"
	extensionv1alpha1 "kubeform.dev/provider-pagerduty-api/apis/extension/v1alpha1"
	maintenancev1alpha1 "kubeform.dev/provider-pagerduty-api/apis/maintenance/v1alpha1"
	responsev1alpha1 "kubeform.dev/provider-pagerduty-api/apis/response/v1alpha1"
	rulesetv1alpha1 "kubeform.dev/provider-pagerduty-api/apis/ruleset/v1alpha1"
	schedulev1alpha1 "kubeform.dev/provider-pagerduty-api/apis/schedule/v1alpha1"
	servicev1alpha1 "kubeform.dev/provider-pagerduty-api/apis/service/v1alpha1"
	teamv1alpha1 "kubeform.dev/provider-pagerduty-api/apis/team/v1alpha1"
	userv1alpha1 "kubeform.dev/provider-pagerduty-api/apis/user/v1alpha1"

	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=addon.pagerduty.kubeform.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("addons"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Addon().V1alpha1().Addons().Informer()}, nil

		// Group=business.pagerduty.kubeform.com, Version=v1alpha1
	case businessv1alpha1.SchemeGroupVersion.WithResource("services"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Business().V1alpha1().Services().Informer()}, nil

		// Group=escalation.pagerduty.kubeform.com, Version=v1alpha1
	case escalationv1alpha1.SchemeGroupVersion.WithResource("policies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Escalation().V1alpha1().Policies().Informer()}, nil

		// Group=event.pagerduty.kubeform.com, Version=v1alpha1
	case eventv1alpha1.SchemeGroupVersion.WithResource("rules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Event().V1alpha1().Rules().Informer()}, nil

		// Group=extension.pagerduty.kubeform.com, Version=v1alpha1
	case extensionv1alpha1.SchemeGroupVersion.WithResource("extensions"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Extension().V1alpha1().Extensions().Informer()}, nil
	case extensionv1alpha1.SchemeGroupVersion.WithResource("servicenows"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Extension().V1alpha1().Servicenows().Informer()}, nil

		// Group=maintenance.pagerduty.kubeform.com, Version=v1alpha1
	case maintenancev1alpha1.SchemeGroupVersion.WithResource("windows"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Maintenance().V1alpha1().Windows().Informer()}, nil

		// Group=response.pagerduty.kubeform.com, Version=v1alpha1
	case responsev1alpha1.SchemeGroupVersion.WithResource("plays"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Response().V1alpha1().Plays().Informer()}, nil

		// Group=ruleset.pagerduty.kubeform.com, Version=v1alpha1
	case rulesetv1alpha1.SchemeGroupVersion.WithResource("rules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ruleset().V1alpha1().Rules().Informer()}, nil
	case rulesetv1alpha1.SchemeGroupVersion.WithResource("rulesets"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ruleset().V1alpha1().Rulesets().Informer()}, nil

		// Group=schedule.pagerduty.kubeform.com, Version=v1alpha1
	case schedulev1alpha1.SchemeGroupVersion.WithResource("schedules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Schedule().V1alpha1().Schedules().Informer()}, nil

		// Group=service.pagerduty.kubeform.com, Version=v1alpha1
	case servicev1alpha1.SchemeGroupVersion.WithResource("dependencies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Service().V1alpha1().Dependencies().Informer()}, nil
	case servicev1alpha1.SchemeGroupVersion.WithResource("eventrules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Service().V1alpha1().EventRules().Informer()}, nil
	case servicev1alpha1.SchemeGroupVersion.WithResource("integrations"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Service().V1alpha1().Integrations().Informer()}, nil
	case servicev1alpha1.SchemeGroupVersion.WithResource("services"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Service().V1alpha1().Services().Informer()}, nil

		// Group=team.pagerduty.kubeform.com, Version=v1alpha1
	case teamv1alpha1.SchemeGroupVersion.WithResource("memberships"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Team().V1alpha1().Memberships().Informer()}, nil
	case teamv1alpha1.SchemeGroupVersion.WithResource("teams"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Team().V1alpha1().Teams().Informer()}, nil

		// Group=user.pagerduty.kubeform.com, Version=v1alpha1
	case userv1alpha1.SchemeGroupVersion.WithResource("contactmethods"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.User().V1alpha1().ContactMethods().Informer()}, nil
	case userv1alpha1.SchemeGroupVersion.WithResource("notificationrules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.User().V1alpha1().NotificationRules().Informer()}, nil
	case userv1alpha1.SchemeGroupVersion.WithResource("users"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.User().V1alpha1().Users().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
