/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-pagerduty-api/apis/ruleset/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRulesets implements RulesetInterface
type FakeRulesets struct {
	Fake *FakeRulesetV1alpha1
	ns   string
}

var rulesetsResource = schema.GroupVersionResource{Group: "ruleset.pagerduty.kubeform.com", Version: "v1alpha1", Resource: "rulesets"}

var rulesetsKind = schema.GroupVersionKind{Group: "ruleset.pagerduty.kubeform.com", Version: "v1alpha1", Kind: "Ruleset"}

// Get takes name of the ruleset, and returns the corresponding ruleset object, and an error if there is any.
func (c *FakeRulesets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Ruleset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rulesetsResource, c.ns, name), &v1alpha1.Ruleset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruleset), err
}

// List takes label and field selectors, and returns the list of Rulesets that match those selectors.
func (c *FakeRulesets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RulesetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rulesetsResource, rulesetsKind, c.ns, opts), &v1alpha1.RulesetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RulesetList{ListMeta: obj.(*v1alpha1.RulesetList).ListMeta}
	for _, item := range obj.(*v1alpha1.RulesetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rulesets.
func (c *FakeRulesets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rulesetsResource, c.ns, opts))

}

// Create takes the representation of a ruleset and creates it.  Returns the server's representation of the ruleset, and an error, if there is any.
func (c *FakeRulesets) Create(ctx context.Context, ruleset *v1alpha1.Ruleset, opts v1.CreateOptions) (result *v1alpha1.Ruleset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rulesetsResource, c.ns, ruleset), &v1alpha1.Ruleset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruleset), err
}

// Update takes the representation of a ruleset and updates it. Returns the server's representation of the ruleset, and an error, if there is any.
func (c *FakeRulesets) Update(ctx context.Context, ruleset *v1alpha1.Ruleset, opts v1.UpdateOptions) (result *v1alpha1.Ruleset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rulesetsResource, c.ns, ruleset), &v1alpha1.Ruleset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruleset), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRulesets) UpdateStatus(ctx context.Context, ruleset *v1alpha1.Ruleset, opts v1.UpdateOptions) (*v1alpha1.Ruleset, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rulesetsResource, "status", c.ns, ruleset), &v1alpha1.Ruleset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruleset), err
}

// Delete takes name of the ruleset and deletes it. Returns an error if one occurs.
func (c *FakeRulesets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rulesetsResource, c.ns, name), &v1alpha1.Ruleset{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRulesets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rulesetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RulesetList{})
	return err
}

// Patch applies the patch and returns the patched ruleset.
func (c *FakeRulesets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Ruleset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rulesetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Ruleset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ruleset), err
}
