/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-pagerduty-api/apis/tag/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAssignments implements AssignmentInterface
type FakeAssignments struct {
	Fake *FakeTagV1alpha1
	ns   string
}

var assignmentsResource = schema.GroupVersionResource{Group: "tag.pagerduty.kubeform.com", Version: "v1alpha1", Resource: "assignments"}

var assignmentsKind = schema.GroupVersionKind{Group: "tag.pagerduty.kubeform.com", Version: "v1alpha1", Kind: "Assignment"}

// Get takes name of the assignment, and returns the corresponding assignment object, and an error if there is any.
func (c *FakeAssignments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Assignment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(assignmentsResource, c.ns, name), &v1alpha1.Assignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assignment), err
}

// List takes label and field selectors, and returns the list of Assignments that match those selectors.
func (c *FakeAssignments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AssignmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(assignmentsResource, assignmentsKind, c.ns, opts), &v1alpha1.AssignmentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AssignmentList{ListMeta: obj.(*v1alpha1.AssignmentList).ListMeta}
	for _, item := range obj.(*v1alpha1.AssignmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested assignments.
func (c *FakeAssignments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(assignmentsResource, c.ns, opts))

}

// Create takes the representation of a assignment and creates it.  Returns the server's representation of the assignment, and an error, if there is any.
func (c *FakeAssignments) Create(ctx context.Context, assignment *v1alpha1.Assignment, opts v1.CreateOptions) (result *v1alpha1.Assignment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(assignmentsResource, c.ns, assignment), &v1alpha1.Assignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assignment), err
}

// Update takes the representation of a assignment and updates it. Returns the server's representation of the assignment, and an error, if there is any.
func (c *FakeAssignments) Update(ctx context.Context, assignment *v1alpha1.Assignment, opts v1.UpdateOptions) (result *v1alpha1.Assignment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(assignmentsResource, c.ns, assignment), &v1alpha1.Assignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assignment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAssignments) UpdateStatus(ctx context.Context, assignment *v1alpha1.Assignment, opts v1.UpdateOptions) (*v1alpha1.Assignment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(assignmentsResource, "status", c.ns, assignment), &v1alpha1.Assignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assignment), err
}

// Delete takes name of the assignment and deletes it. Returns an error if one occurs.
func (c *FakeAssignments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(assignmentsResource, c.ns, name), &v1alpha1.Assignment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAssignments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(assignmentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AssignmentList{})
	return err
}

// Patch applies the patch and returns the patched assignment.
func (c *FakeAssignments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Assignment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(assignmentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Assignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Assignment), err
}
