/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-pagerduty-api/apis/user/v1alpha1"
	scheme "kubeform.dev/provider-pagerduty-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ContactMethodsGetter has a method to return a ContactMethodInterface.
// A group's client should implement this interface.
type ContactMethodsGetter interface {
	ContactMethods(namespace string) ContactMethodInterface
}

// ContactMethodInterface has methods to work with ContactMethod resources.
type ContactMethodInterface interface {
	Create(ctx context.Context, contactMethod *v1alpha1.ContactMethod, opts v1.CreateOptions) (*v1alpha1.ContactMethod, error)
	Update(ctx context.Context, contactMethod *v1alpha1.ContactMethod, opts v1.UpdateOptions) (*v1alpha1.ContactMethod, error)
	UpdateStatus(ctx context.Context, contactMethod *v1alpha1.ContactMethod, opts v1.UpdateOptions) (*v1alpha1.ContactMethod, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ContactMethod, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ContactMethodList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ContactMethod, err error)
	ContactMethodExpansion
}

// contactMethods implements ContactMethodInterface
type contactMethods struct {
	client rest.Interface
	ns     string
}

// newContactMethods returns a ContactMethods
func newContactMethods(c *UserV1alpha1Client, namespace string) *contactMethods {
	return &contactMethods{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the contactMethod, and returns the corresponding contactMethod object, and an error if there is any.
func (c *contactMethods) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ContactMethod, err error) {
	result = &v1alpha1.ContactMethod{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("contactmethods").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ContactMethods that match those selectors.
func (c *contactMethods) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ContactMethodList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ContactMethodList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("contactmethods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested contactMethods.
func (c *contactMethods) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("contactmethods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a contactMethod and creates it.  Returns the server's representation of the contactMethod, and an error, if there is any.
func (c *contactMethods) Create(ctx context.Context, contactMethod *v1alpha1.ContactMethod, opts v1.CreateOptions) (result *v1alpha1.ContactMethod, err error) {
	result = &v1alpha1.ContactMethod{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("contactmethods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(contactMethod).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a contactMethod and updates it. Returns the server's representation of the contactMethod, and an error, if there is any.
func (c *contactMethods) Update(ctx context.Context, contactMethod *v1alpha1.ContactMethod, opts v1.UpdateOptions) (result *v1alpha1.ContactMethod, err error) {
	result = &v1alpha1.ContactMethod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("contactmethods").
		Name(contactMethod.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(contactMethod).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *contactMethods) UpdateStatus(ctx context.Context, contactMethod *v1alpha1.ContactMethod, opts v1.UpdateOptions) (result *v1alpha1.ContactMethod, err error) {
	result = &v1alpha1.ContactMethod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("contactmethods").
		Name(contactMethod.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(contactMethod).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the contactMethod and deletes it. Returns an error if one occurs.
func (c *contactMethods) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("contactmethods").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *contactMethods) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("contactmethods").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched contactMethod.
func (c *contactMethods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ContactMethod, err error) {
	result = &v1alpha1.ContactMethod{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("contactmethods").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
