/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-pagerduty-api/apis/service/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEventRules implements EventRuleInterface
type FakeEventRules struct {
	Fake *FakeServiceV1alpha1
	ns   string
}

var eventrulesResource = schema.GroupVersionResource{Group: "service.pagerduty.kubeform.com", Version: "v1alpha1", Resource: "eventrules"}

var eventrulesKind = schema.GroupVersionKind{Group: "service.pagerduty.kubeform.com", Version: "v1alpha1", Kind: "EventRule"}

// Get takes name of the eventRule, and returns the corresponding eventRule object, and an error if there is any.
func (c *FakeEventRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EventRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(eventrulesResource, c.ns, name), &v1alpha1.EventRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventRule), err
}

// List takes label and field selectors, and returns the list of EventRules that match those selectors.
func (c *FakeEventRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EventRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(eventrulesResource, eventrulesKind, c.ns, opts), &v1alpha1.EventRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EventRuleList{ListMeta: obj.(*v1alpha1.EventRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.EventRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested eventRules.
func (c *FakeEventRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(eventrulesResource, c.ns, opts))

}

// Create takes the representation of a eventRule and creates it.  Returns the server's representation of the eventRule, and an error, if there is any.
func (c *FakeEventRules) Create(ctx context.Context, eventRule *v1alpha1.EventRule, opts v1.CreateOptions) (result *v1alpha1.EventRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(eventrulesResource, c.ns, eventRule), &v1alpha1.EventRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventRule), err
}

// Update takes the representation of a eventRule and updates it. Returns the server's representation of the eventRule, and an error, if there is any.
func (c *FakeEventRules) Update(ctx context.Context, eventRule *v1alpha1.EventRule, opts v1.UpdateOptions) (result *v1alpha1.EventRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(eventrulesResource, c.ns, eventRule), &v1alpha1.EventRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEventRules) UpdateStatus(ctx context.Context, eventRule *v1alpha1.EventRule, opts v1.UpdateOptions) (*v1alpha1.EventRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(eventrulesResource, "status", c.ns, eventRule), &v1alpha1.EventRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventRule), err
}

// Delete takes name of the eventRule and deletes it. Returns an error if one occurs.
func (c *FakeEventRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(eventrulesResource, c.ns, name), &v1alpha1.EventRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEventRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(eventrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EventRuleList{})
	return err
}

// Patch applies the patch and returns the patched eventRule.
func (c *FakeEventRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EventRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(eventrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.EventRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventRule), err
}
