/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	tagv1alpha1 "kubeform.dev/provider-pagerduty-api/apis/tag/v1alpha1"
	versioned "kubeform.dev/provider-pagerduty-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-pagerduty-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-pagerduty-api/client/listers/tag/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AssignmentInformer provides access to a shared informer and lister for
// Assignments.
type AssignmentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AssignmentLister
}

type assignmentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAssignmentInformer constructs a new informer for Assignment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAssignmentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAssignmentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAssignmentInformer constructs a new informer for Assignment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAssignmentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TagV1alpha1().Assignments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TagV1alpha1().Assignments(namespace).Watch(context.TODO(), options)
			},
		},
		&tagv1alpha1.Assignment{},
		resyncPeriod,
		indexers,
	)
}

func (f *assignmentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAssignmentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *assignmentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tagv1alpha1.Assignment{}, f.defaultInformer)
}

func (f *assignmentInformer) Lister() v1alpha1.AssignmentLister {
	return v1alpha1.NewAssignmentLister(f.Informer().GetIndexer())
}
